package com.edw.project01;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.Integer age;

	public User() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public User(java.lang.String name, java.lang.Integer age) {
		this.name = name;
		this.age = age;
	}

}